### ISSUE TITLE
Can't edit this existing published paper

### ISSUE THREAD

**Issue by ryanseslow** [cuny-academic-commons/social-paper#102]
Hello,
The Edit button does not seem to work or allow me to edit this existing paper (there are so many typos I want to fix :(

the link is - https://commons.gc.cuny.edu/papers/53657/

I also see some wonky code in the left hand side bar area of the expanded web page.

Any help would be appreciated.
:)
<img width="2162" alt="Screen Shot 2022-10-13 at 8 56 33 AM" src="https://user-images.githubusercontent.com/21285648/195602383-1a64f74c-8db2-46ee-b433-02b506188ba6.png">

**Comment by boonebgorges** [comment]
Hi @ryanseslow - Thanks for the ticket and the screenshot.

We've more or less deprecated the use of social-paper on the CUNY Academic Commons. For technical reasons, it's not feasible at the moment to re-enable editing. However, I'm able to update text - if you'd like to send me an updated version of the copy, or specific edits, I can swap it out.

Sorry for the inconvenience!

**Comment by ryanseslow** [comment]
Thanks so much Boone! I totally understand, for some reason this seems to be a popular paper and I still get a ton of inquiries to this day! :) - Those same peeps also alert me to the fact that there are a few typos with the word "due" instead of "do"..  and with "you".. that should be "your" If those few can be updated I would really appreciate it!
Im attaching a screen shot to locate them :)))
Thank you thank you!
Ryan
<img width="1247" alt="Screen Shot 2022-10-13 at 12 38 29 PM" src="https://user-images.githubusercontent.com/21285648/195662088-098a7f98-6ade-4253-bc6c-de606e31a117.png">
<img width="1233" alt="Screen Shot 2022-10-13 at 12 37 37 PM" src="https://user-images.githubusercontent.com/21285648/195662097-ac3da525-fe10-4393-b280-2e38b6eb80a4.png">

**Comment by boonebgorges** [comment]
Thanks, @ryanseslow ! Taking a second look, I think it might be easier for me to grant Dashboard access for you to make your mods directly. Could you let me know whether you're able to see the paper in question when you visit https://commons.gc.cuny.edu/wp-admin/edit.php?post_type=cacsp_paper? If so, please go ahead and make your edits, and let me know when you're done so that I can hide the menu item again.

**Comment by ryanseslow** [comment]
Hi Boone!
Thank you!!
Yes I can see it and will apply the edits this evening!

Thank you so much!
:)))
Ryan


Ryanseslow.com
@ryanseslow


On Oct 18, 2022, at 10:09 AM, Boone Gorges ***@***.***> wrote:

﻿

Thanks, @ryanseslow<https://github.com/ryanseslow> ! Taking a second look, I think it might be easier for me to grant Dashboard access for you to make your mods directly. Could you let me know whether you're able to see the paper in question when you visit https://commons.gc.cuny.edu/wp-admin/edit.php?post_type=cacsp_paper? If so, please go ahead and make your edits, and let me know when you're done so that I can hide the menu item again.

**Comment by ryanseslow** [comment]
Hi Boone,
I made the edits and updated the post!
Thank you again for the help!
🙂
Ryan
________________________________

**Comment by boonebgorges** [comment]
Thanks for confirming!
