### ISSUE TITLE
Profile setup happens before 'init'

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#19]
We're registering post types and taxonomies at 'init', but a bunch of profile setup is happening at 'plugins_loaded' (that is, 'bp_setup_nav'), and some of that profile setup involves doing post type queries (such as user paper counts). This is causing weird results, especially as I try to filter out results based on access protections (#18). Can we remove this counting, or move it later in the bootstrap?

**Comment by r-a-y** [comment]
Go ahead and remove the count.  It also helps to reduce queries when on 
a BP page, since the count is currently uncached.

**Comment by boonebgorges** [comment]
Cool, thanks! I see you have some caching in there, but commented it out :)

I'm only going to remove it in the profile nav. Directory navigation is 
loaded late enough for it to be a non-issue.

**Comment by r-a-y** [comment]
> Cool, thanks! I see you have some caching in there, but commented it out :)

Actually, @christianwach implemented the profile count and caching originally.

**Comment by boonebgorges** [comment]
Oops! Next time I'll use my blame tools.
