### ISSUE TITLE
Comment moderation

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#27]
What should we do about comment moderation? Currently, the plugin obeys WP Discussion settings. This means that, in some cases, comments are held for moderation. But there's no obvious way for authors to moderate comments. Should we force-approve comments from logged-in users? Any ideas? :-D
- [x] Add moderation links to settings sidebar when there are unapproved comments
- [x] Intercept WP's moderation emails and replace the links
- [x] Don't send comment notification emails until a comment is approved
- [x] After spamming/trashing a comment, page should reopen in Edit mode
- [x] After spamming/trashing a comment, there should be some feedback
- [x] Nice to have: an unmoderated comment count bubble (I'm thinking a number in a little red circle) that appears in various places. Minimally, over the Settings toggle button, but perhaps also in directories.

**Comment by mkgold** [comment]
Since we are working within a trusted network, I would say yes to "Should we force-approve comments from logged-in users?"

I guess another question is whether non-logged-in users can add comments

**Comment by r-a-y** [comment]
> I guess another question is whether non-logged-in users can add comments

Yes they can.  If we do not want non-logged in users to comment, we can use WP's "Settings > Discussion" settings to toggle this off.

> Should we force-approve comments from logged-in users?

I would also say "yes" to this as well.  We should do this for our post type only though.

**Comment by boonebgorges** [comment]
> Yes they can. If we do not want non-logged in users to comment, we can use WP's "Settings > Discussion" settings to toggle this off.

Thinking about this - checking this box will prevent non-logged-in users from commenting on any post type throughout the site, which is not necessarily what we want. For v1, I think we should simply limit comments to logged-in users programatically, and for a future version we can come up with a better moderation system.

**Comment by sheesh** [comment]
I want to push against limiting comments to logged-in users
programmatically for the first version. One of the ways I plan to promote
SP is by eliciting comments from non-Commons members with the hopes of
showing how SP can build audiences across institutions.

One way of solving this is to refurbish the directory to follow the
"groups" template with a left side bar (instead of the toggle options that
are currently in place). One of the nav items on the side bar could be
"received comments" where users would go to approve comments. The other nav
items would include "all papers," "my papers," and "papers shared with me."
I will do a wire frame today to supplement the one Samantha made based on
our meeting yesterday.

erin rose glass | digital fellow | cuny grad center | nyc
www.erinroseglass.com | @erinroseglass

**Comment by boonebgorges** [comment]
> I want to push against limiting comments to logged-in users programmatically for the first version.

I don't want to be the one to make the call here. Things like this take time to build, so the more we include in the first version, the longer things are going to take. But if this is critical for the first ("minimal") version, then your idea sounds fine.

**Comment by sheesh** [comment]
Good point. I don't want to add too much time to development. Please see
the mock up I emailed that mimics "Group" layout. Perhaps this would solve
several problems at once.

erin rose glass | digital fellow | cuny grad center | nyc
www.erinroseglass.com | @erinroseglass

**Comment by mkgold** [comment]
Hi All,

I'm fine with leaving non-logged-in comments off of the MVP if we don't have a reasonably developed system to handle comment moderation. I have doubts about whether the hub is the best place for comment moderation; for one thing, if there was a notification of comments placed in moderation, it would be weird to be taken to a hub page to approve/disapprove. 

Are comments from logged-in users visible to non-logged-in users?

**Comment by boonebgorges** [comment]
Comment visibility obeys general paper visibility. Anyone can see 
anything on a public paper, and only whitelisted members can see the 
content/comments of a protected paper.

**Comment by mkgold** [comment]
So the comment icon has two functions -- both adding comments and viewing
comments? Ie., that icon will appear even for non-logged-in users?

**Comment by boonebgorges** [comment]
I guess you could put it this way. I'd say: The comment bubble expands 
the comment section for that paragraph. The comment section includes 
both the list of existing comments and the comment form. If the current 
user is not logged in, and logged-out commenting is disabled, the 
comment form will consist of a message that says "You must be logged in 
to comment".

**Comment by mkgold** [comment]
Thanks -- that makes sense.

**Comment by sheesh** [comment]
I'm still very concerned about losing the possibility for non-logged in
users to comment. This is vital to SP's vision. If my suggestion regarding
the location of comment moderation is not feasible (I did not suggest the
hub just to be clear), then perhaps there is another way, such as within
the comment itself? I'd prefer a very clunky solution to no possibility at
all.

If this is still not possible, when do you think we could expect
implementing this feature? I will be writing about Social Paper on the site
and will be soliciting comments from interested participants; most of which
are not CAC members. I want to show CAC members what it can look like to
build a community around one's work that transcends one's institution.

erin rose glass | digital fellow | cuny grad center | nyc
www.erinroseglass.com | @erinroseglass

**Comment by boonebgorges** [comment]
If it's critical for the first version, then we'll do it. I'm working on it.

**Comment by sheesh** [comment]
Thank you! Sorry to be such a stickler on this point. I know you have been
working non stop!

On Sunday, October 25, 2015, Boone Gorges notifications@github.com wrote:

> If it's critical for the first version, then we'll do it. I'm working on
> it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cuny-academic-commons/social-paper/issues/27#issuecomment-151014205
> .

##

**Comment by boonebgorges** [comment]
First pass at this is in 87fbb7e. A bunch of things need to be fixed before it's usable. I've updated the ticket description with some todos for myself.
