### ISSUE TITLE
Link Papers to Groups

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#3]
Much of the required code can be ported from bp-event-organiser.

**Comment by r-a-y** [comment]
@boonebgorges Just a heads-up, I created a new branch - `beta2` - to separate your work on activity/group integration and so I can get fixes for the test team on cdev.

I'll cherry-pick whatever commits I make to `beta2` to `master` so no need to worry there.

**Comment by boonebgorges** [comment]
Sounds good - I was wondering what was going to happen there. Thanks @r-a-y!

**Comment by boonebgorges** [comment]
I think this is mainly done. Here's an outline for posterity:
- When a paper is added to a group (either an existing paper or a new one), each group gets an "Added to group" activity item. This activity item is deleted when the paper is disconnected from the group.
- There's a Groups section in the sidebar panel that allows associating with multiple groups.
- When a paper is Protected, members of connected groups will be whitelisted for access.
- Edits and comments related to group papers are inserted into the group activity stream.

There will probably be some cleanup to do related to BPGES. I'll open a separate ticket.
