### ISSUE TITLE
Don't highlight slug when creating paper

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#32]
Related: #31 

It's possible this will be most easily fixed upstream.

**Comment by r-a-y** [comment]
I think we should keep the slug highlighted to let authors know that the slug is editable.

Perhaps when the user clicks inside the URL box, the slug becomes highlighted instead?

**Comment by mkgold** [comment]
> Perhaps when the user clicks inside the URL box, the slug becomes highlighted instead?

That sounds perfect to me. I just don't think it should be highlighted to start, because the title and body of the paper are also editable and arguably should be addressed by the user before the slug.

**Comment by boonebgorges** [comment]
The paper can be edited too - that's the important part - and we don't 
highlight that.

If we do a better job of auto-generated slugs, this won't be an issue. 
I'm almost finished with #31 - once it's done, I think we'll be in a 
better position to say what to do about this ticket.

> Perhaps when the user clicks inside the URL box, the slug becomes
> highlighted instead?

Yeah, this sounds good.
