### ISSUE TITLE
Put a "beta" label somewhere in the interface

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#33]
For the initial rollout, we should put the "beta" label somewhere prominent in the interface.

The "beta" notification could play a double (or triple or quadruple) role:
- could contain CAC branding, in which case it'd have to be a CAC-only feature
- can be coupled with link to paper hub, addressing some concerns about navigability
- should contain a link to submit a bug report

**Comment by boonebgorges** [comment]
@samradd Could you or @chris0stein give a sense of what this label and/or link to the hub should look like?

**Comment by samradd** [comment]
It's very hard to do this without cluttering the interface. I suggest we use the top-nav to our advantage here, similar to when users are editing a site, and include a button back to the hub there. A colored alert bar could be the main indicator that this is beta and include the links to the codex articles on Social Paper as well as a bug-reporting link (does this lead to Redmine or Zendesk?). 

![social paper nav](https://cloud.githubusercontent.com/assets/7431171/11004991/443a8c64-8489-11e5-8315-7bccf666076d.jpg)

**Comment by mkgold** [comment]
Thanks, Sam -- the top-nav link is in line with what I thought we had decided, so that looks good. And I like the blue colored alert.

**Comment by boonebgorges** [comment]
This looks fine to me. A couple questions:
- The toolbar link goes to the Hub, right?
- Does the blue bar show in Edit mode too?
- Should the blue bar be fixed to the toolbar, so that it's still visible when scrolled down, or part of the scrollable content of the page, so it disappears when scrolling down?

cc @r-a-y

**Comment by r-a-y** [comment]
Looks nice!

> Does the blue bar show in Edit mode too?

I would say no, but when you disable editing, the blue bar will show again.

> Should the blue bar be fixed to the toolbar, so that it's still visible when scrolled down, or part of the scrollable content of the page, so it disappears when scrolling down?

I would say that the blue bar shouldn't be fixed.  The WP admin bar is already fixed and that takes up some vertical space.  Adding two bars that are fixed right next to each other isn't that pleasing aethestically in my opinion.

**Comment by boonebgorges** [comment]
(I agree with @r-a-y on both points! But I would like to get the green light from the others too.)

**Comment by mkgold** [comment]
I agree, as well.

**Comment by samradd** [comment]
> The toolbar link goes to the Hub, right?

Yessir.

> Does the blue bar show in Edit mode too?

Since we're including the link bug reports and it's possible that people's first interactions with it are via creating a paper rather than just reading/commenting, yes, it should show in edit mode too.

> Should the blue bar be fixed to the toolbar, so that it's still visible when scrolled down, or part of the scrollable content of the page, so it disappears when scrolling down?

I'd love for it to be always visible (for the same reasons as the previous point), but would be willing to give up it's "stickyness" if it's in both edit and view mode.

**Comment by boonebgorges** [comment]
> Since we're including the link bug reports and it's possible that people's first interactions with it are via creating a paper rather than just reading/commenting, yes, it should show in edit mode too.

Yeah, I was on the fence about this. I think that (a) showing it in Edit mode, but (b) allowing it to scroll offscreen is a decent compromise.

@r-a-y Can I ask you to implement?

**Comment by r-a-y** [comment]
First pass is up on cdev.

I've made sure it's responsive.  "Report Bug" is currently linked to the Github issues page.  Let me know where this should be properly linked.

**Comment by boonebgorges** [comment]
Awesome, thanks! I think the scroll works nicely - the blue makes it very noticeable, but I can easily scroll it out of view.

The Report Bug should definitely _not_ go to Github :) I would suggest that instead of "Report Bug", it should read "Support" or "Help", and should point to a static documentation page; that page would then urge people to submit problems through Zendesk.

**Comment by mkgold** [comment]
Agree that it would be great to tie "Report Bug" to our existing bug-reporting system through Zendesk

**Comment by samradd** [comment]
I'm loving the blue-bar functionality! 
Is adding the 'Social Paper (beta)' button to the right of the site menu in the persistent WP header nav still in the plan?

![](https://cloud.githubusercontent.com/assets/7431171/11004991/443a8c64-8489-11e5-8315-7bccf666076d.jpg)

**Comment by r-a-y** [comment]
@samradd - Sorry about the omission of the "Social Paper (beta)" menu item in the WP admin bar.  I missed that!

Is it necessary though with the inclusion of the blue beta bar?

**Comment by samradd** [comment]
No problem!

Yes, so that there's a surfaced way back to the hub from within editing or reading papers that remains even after beta is over and the blue bar has been removed. I'm imagining that 'About Social Paper' will lead to the codex page once that's live, rather than back to the hub. And I've had a couple people take quick looks at this interface and they both commented that they weren't sure how to "get out".

**Comment by r-a-y** [comment]
Gotcha!

Will implement.

**Comment by r-a-y** [comment]
`Social Paper (beta)` admin bar menu item is now implemented on cdev.
