### ISSUE TITLE
Font size should be smaller

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#34]
I think we pretty much just aped Medium here, but @sheesh has requested that we reduce the font size for read mode. I think we need to be careful not to turn this thing into MS Word - just because it's what people are used to doesn't mean it's good - but I think it's worth considering a change of some sort. Assigning to @samradd for consideration.

**Comment by samradd** [comment]
I think smaller could be good -- it's quite intense on my 11" laptop, but I agree that we don't need to totally shrink it. How about 4px smaller for the header and text, which I believe converts them to a 44px header and 18px body.

**Comment by boonebgorges** [comment]
I've made the fonts smaller, as Sam suggested. This can be reviewed on cdev.

**Comment by samradd** [comment]
Looks good to me. @sheesh are you happy with font size now?

**Comment by sheesh** [comment]
looks good!
