### ISSUE TITLE
Allow authors to provide a paper excerpt/summary

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#38]
For display in directories, etc.

**Comment by mkgold** [comment]
Can/should an excerpt be auto-generated for papers where authors don't provide a summary? (ie, taking the first x number of lines/characters as the excerpt)

**Comment by boonebgorges** [comment]
Yeah, but I don't think we want to institute the feature without 
allowing authors to customize it. In the case of papers (maybe more than 
in the case of blog posts) it's probably going to be very common for 
people to want to customize the excerpt.

**Comment by mkgold** [comment]
So -- maybe the excerpt is auto-generated for the directory if the excerpt field is left blank?

Also, there is the question of where to put this field on the page . . .

**Comment by boonebgorges** [comment]
> So -- maybe the excerpt is auto-generated for the directory if the
> excerpt field is left blank?

Yup, agreed.

> Also, there is the question of where to put this field on the page

Right. That's why I opened a ticket instead of just doing it :)

**Comment by mkgold** [comment]
Okay. I'd argue for putting it below the paper, but I'd be interested in seeing what other writing interfaces do. @samradd @sheesh, any thoughts?

**Comment by sheesh** [comment]
I think that's fine.

erin rose glass | digital fellow | cuny grad center | nyc
www.erinroseglass.com | @erinroseglass

**Comment by samradd** [comment]
I'm afraid it will get lost below the paper, especially if it's very long. Up top is the most logical, but I know we don't want to clutter the interface much. How about in the settings panel?

**Comment by sheesh** [comment]
I like that idea as well.

erin rose glass | digital fellow | cuny grad center | nyc
www.erinroseglass.com | @erinroseglass

**Comment by mkgold** [comment]
Hi Sam,

Would it get lost on the page if it is near the "publish/save" button?

**Comment by boonebgorges** [comment]
The Settings panel makes the most sense to me. If it were near "Publish", I guess it'd have to pop up a modal?

**Comment by mkgold** [comment]
Just checked CDEV and saw the settings panel for the first time. Is this new as of the BP integration phase?

**Comment by boonebgorges** [comment]
Yes

**Comment by profstein** [comment]
I also agree that the Settings panel makes the most sense.

**Comment by boonebgorges** [comment]
I've implemented this. There's now a Description input in the settings sidebar. It suggests, though doesn't enforce, a 250 character count. I called it "Description" rather than "Excerpt" because I thought it was more appropriate for the use of the field. The description is then shown as appropriate in directories.
