### ISSUE TITLE
After creating a paper, page should refresh

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#39]
If for no other reason than that FEE doesn't change the text of the "Publish" button dynamically.

**Comment by r-a-y** [comment]
I think we can close this one.

When a paper is published, we're now dynamically changing the draft URL to the real paper URL and the "Publish" button is now changed to "Update".

**Comment by boonebgorges** [comment]
Reopening this issue. From http://commons.gc.cuny.edu/?p=44087:

> When I Create New Paper/Type some blocks/Save Draft/Add some more blocks
> Then Clicking Update publishes my paper.

I guess we should be refraining from swapping the URL when the paper status is not 'publish'?

**Comment by r-a-y** [comment]
> I guess we should be refraining from swapping the URL when the paper status is not 'publish'?

I still think it's good to swap the URL, but only during publishing and not during drafts.  Will work on this later today.

**Comment by boonebgorges** [comment]
Yup, that's what I meant. (The on-publish swapping is very slick.) Thanks!
