### ISSUE TITLE
Activity + notification integration

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#4]

**Comment by boonebgorges** [comment]
Hey @r-a-y - Check out 9913e41. As far as I could see, this is the only general way to tap into the 'filter_query' early enough for `BP_Activity_Activity::get()` to parse it. That's because (a) `get()` always gives precedence to 'scope', so that 'scope' must be unset in time; and (b) `get()` will parse 'filter' args separately from the 'filter_query', and they'll be attached with an `AND` clause, which won't work in our case.

In BuddyPress, I think we should retool `get()` so that filter_query is the "canonical" filter clause, and all other arguments would be processed, in a serial fashion, into a `BP_Activity_Query` object, which would be responsible for spitting out the WHERE clause. So the logic would be:

```
if ( isset( $scope ) ) {
    // Convert the scope to filter query args, and add them to 'filter_query'
}

if ( isset( $filter ) ) {
    // Convert the filter to filter_query args, and add them to filter_query
}

if ( ! empty( $filter_query ) ) {
    $fq = new BP_Activity_Query( $filter_query );

    // This would be the generic filter point for plugins wanting to modify the WHERE clauses
    $fq = apply_filters( ... );

    $filter_sql = $fq->get_sql();
}
```

We'd have to have some magic that would ensure that 'scope' takes proper precedence, etc. But the key is to enforce that all logic runs through a single `BP_Activity_Query` instance, so that it can be filtered once. 

What do you think? If the above sketch seems good to you, I can work on a BP patch.

**Comment by r-a-y** [comment]
I've been meaning to open a ticket about having 'filter' be its own 
thing so it isn't conditional from 'scope' being set so this sounds good 
to me!

+1.

**Comment by boonebgorges** [comment]
Thanks! I think this'll open the door to some cool things, including 
better integration of 'hide_sitewide' stuff into logged-in activity 
streams in BP.

**Comment by boonebgorges** [comment]
Thanks, @r-a-y! Here's the ticket: 
https://buddypress.trac.wordpress.org/ticket/6645#ticket

I'll work on a patch in the upcoming weeks, but in the meantime, if you 
have specific or high-level thoughts, I'd love to hear them.

**Comment by boonebgorges** [comment]
This should be pretty much done. A summary:
- When a paper is created, a single 'new_cacsp_paper' item is created. We're using BP's relatively new CPT internals for this.
- When a paper is edited, a single 'new_cacsp_edit' item is created. This item uses the author of the most recent revision for the activity 'user_id'. It also contains a brief excerpt that should contain the first edit in the latest revision. Edit activity is throttled: no more than one edit activity item per paper in a 6 hour period.
- When someone leaves a comment on a paper, a 'new_cacsp_comment' activity item is created.
- All of these activity items are subject to access protection. That is, activity related to Protected papers is visible only to people who have the permission to view the papers themselves.

**Comment by boonebgorges** [comment]
Just realized I closed this without addressing, or even thinking about :) , notifications. (by which I mean BP notifications) I'm going to open a separate ticket for this.
