### ISSUE TITLE
Improved support for papers without titles

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#40]
When a paper doesn't have a title, it messes up things like directories, activity text, email notifications, etc. We should do one of two things:
- Make sure that the text in these various interfaces supports untitled papers. So "Boone edited the paper 'Foo'" becomes "Boone edited a paper" or "Boone edited an untitled paper" or whatever. This is going to be a lot of work, because there are going to be lots of places like this.
- Alternatively, we could enforce that the title cannot be blank. I don't know how hard this is going to be with FEE.

**Comment by mkgold** [comment]
Could we auto-generate a title like "Untiled Paper 1" and "Untitled Paper 2"? Would that make things easier?

**Comment by r-a-y** [comment]
In the Paper Directory, when there is no title, the title lists `(Untitled)`.
