### ISSUE TITLE
New papers not recorded into the activity stream

### ISSUE THREAD

**Issue by r-a-y** [cuny-academic-commons/social-paper#44]
Might have something to do with some custom code we're running to update the paper at various junctures (tags, post title).

New papers do get recorded when posting a new paper from the WP admin area though.

**Comment by boonebgorges** [comment]
Hm, I'm 99% sure this worked at some point. It's worth a bisect back to 
the changeset where it was originally introduced.

But yeah, it could have something to do with the /papers/new/ juggling act.

**Comment by r-a-y** [comment]
@boonebgorges - We might want to add a filter like the folllowing into BP core:

```
add_filter( 'bp_activity_content_before_save', 'htmlentities' );
```

To prevent issues like this from popping up elsewhere.

**Comment by boonebgorges** [comment]
Whoa. This sounds terrible. What were the problematic characters? What's 
your database encoding?

**Comment by r-a-y** [comment]
My `wp_bp_activity` `content` column is `utf8_general_ci`.

The characters when I converted them via `urlencode()` were `%0A%0A%A0`.

The fact that this issue doesn't occur when posting via the WP admin interface means that some filters are missing when posting via FEE, which trickles down to BuddyPress and caused this bug.

**Comment by boonebgorges** [comment]
Hm, yeah. BP should probably even have sanity checks, deeper down, which 
detect `$wpdb->insert()` failures, then try stripping invalid characters 
before attempting another insert. WP does this for posts, for instance.

**Comment by r-a-y** [comment]
Turns out we do have a ticket about this on BuddyPress Trac:
https://buddypress.trac.wordpress.org/ticket/6346#comment:16
