### ISSUE TITLE
Directories

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#5]
- Top-level directory (CPT archive?): example.com/paper
- Group tabs
- Member tabs

These can probably share some common template parts.

For group and member tabs, I'm thinking they only need to appear if the group/member actually has papers to show. No need for settings pages as part of the first pass.

---

Todo:
- [x] Root directory - AJAX tabs (My Papers) (commits 1880a1d / 96693c6)
- [x] Root directory - AJAX search (commits 1880a1d / 96693c6)

**Comment by r-a-y** [comment]
I've made a first pass at overriding the content on the CPT archive page - `example.com/paper/`,  You need to refresh permalinks by going to "Settings > Permalinks" to see this in action.

Template to customize is `/templates/content-directory-social-paper.php`.

**Comment by christianwach** [comment]
Am building today... but a quick question - should I build a full BP_Component here? Do we want a BP-style directory if enabled?

**Comment by boonebgorges** [comment]
BP_Component builds the user-directory 
(example.com/members/boone/papers/), and provides some minimal support 
for registering a root-level directory (example.com/papers) via 
has_directory=true and root_slug). We want both kinds of directories. 
But I would suggest that we only use BP_Component for the first kind, 
and handle the second kind through WP's native template hierarchy.

**Comment by christianwach** [comment]
@boonebgorges thanks. I've been building without a component thus far. Seems like an unnecessary extra step for people if BP is installed - '/members/username/papers' works fine without the need to enable a component if we're not using a BP-style directory. Is there a compelling advantage that I'm missing?

**Comment by boonebgorges** [comment]
Can you say more about what a "BP-style directory" is, and how it 
differs from what you're doing now?

BP_Component is a way to register globals - a data structure. If all 
you're doing is registering a new nav item, then you probably don't need it.

**Comment by christianwach** [comment]
> Can you say more about what a "BP-style directory" is, and how it differs from what you're doing now?

Sure. What I'm referring to is akin to a BP page such as the Members Directory, the Groups Directory or the Sites Directory. They all share a common look and feel, with a search box and generally a "New Thing..." button. I implemented this on the IHC site for Papers and Paper Authors.

**Comment by christianwach** [comment]
> and how it differs from what you're doing now?

At present, I'm creating a nav item on Member profiles with two subnav items: "Published" and "Drafts". These simply pull in lists of papers like the CPT archive does. It's pretty minimal by comparison to the richer BP-style directory UI.

**Comment by boonebgorges** [comment]
Oh, ok. I don't have any definite thoughts about what it should look 
like, though I have a feeling it's going to make the most sense to make 
the Papers directory look more or less like the other kinds of directories.

It's not important to me to use BP_Component for this. BP_Component 
provides minimal tools, like directory_title and search_string, for 
building this page. Using BP_Component means that sites without BP will 
be stuck with a standard-issue CPT archive template, which IMO is not 
good enough.

So, let's make the archive template fully functional (I assume this 
qualifies as a "BP-style directory", though I'm less concerned with 
making it look like other BP directories than I am about having it be 
full-featured) but let's not use BP_Component to do it.

**Comment by christianwach** [comment]
> So, let's make the archive template fully functional

:grinning: Sounds like a plan.

**Comment by christianwach** [comment]
Stubs added for profiles and groups in 9f1889e36af9adf1f1456b00b81f3774539f639a. Output isn't in external templates because of the custom `WP_Query`.

**Comment by boonebgorges** [comment]
WP_Query now supports a 'bp_group' param, so you can do something like

```
 'post_type' => 'cacap_paper',
 'bp_group' => bp_get_current_group_id(),
```

We'll have to talk about how (or whether) this works with a loop 
template that's shared between groups + users + global directory.

**Comment by christianwach** [comment]
I've been wondering about that. Seems to me that the text is significantly different for each use case. The markup could be externalised, but then the queries would have to be globals wouldn't they?

**Comment by boonebgorges** [comment]
The whole thing is complicated by the fact that the CPT archive page uses the _main_ query, while we have a nested query on the user and group pages.

Let's just use template parts for the pieces that need repeating. So the CPT archive will be something like:

```
if ( have_posts() ) {
    get_template_part( '/path/to/social-paper-dir-header.php' ); // nav, search, etc

    while ( have_posts ) : the_post();
        get_template_part( '/path/to/social-paper-single-item.php' );
    endwhile;
```

   }

That way there'll be minimal duplication between the different template contexts.

**Comment by r-a-y** [comment]
> The whole thing is complicated by the fact that the CPT archive page uses the main query

Yeah, I made this decision initially based on the fact that not everyone will be using BuddyPress.  If it makes things easier, we can always revert back to the BP directory way.

**Comment by boonebgorges** [comment]
It doesn't matter that much. We could share the template completely, 
though it'll mean that on the global directory we fire the query twice.

**Comment by christianwach** [comment]
To what extent are we building generically? I thought this was CAC-specific initially

**Comment by boonebgorges** [comment]
CAC-specific initially, but where it's minimal effort to support non-CAC 
and non-BP, do it.

**Comment by christianwach** [comment]
> CAC-specific initially, but where it's minimal effort to support non-CAC and non-BP, do it.

Sounds reasonable.

**Comment by r-a-y** [comment]
I've introduced the `cacsp_get_template_part()` function in commit a01cae0.  It's exactly the same as `get_template_part()`, but supports our custom template directory.

This should make things easier to re-use template parts in BP contexts and on the CPT archive.

**Comment by christianwach** [comment]
@r-a-y Sweet. Fixed a typo, but now works fine.

**Comment by christianwach** [comment]
I'm not sure about the naming scheme I've given the template files. Anyone with a better scheme, please implement to your tastes!

**Comment by r-a-y** [comment]
Going to close this one as this is pretty much complete now.
