### ISSUE TITLE
Move author box to the top of the page

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#55]
I'm not sure what kind of ramifications this will have for scripts etc, so I'm putting it in the 1.0 milestone only tentatively.

**Comment by boonebgorges** [comment]
I don't see any weird side effects from the move, so I'm going to call it closed.

I've opted to put it above the title (as shown in https://www.evernote.com/shard/s11/sh/2a92f7ca-7297-4a88-95fe-e21552e776be/3ad953afd37528809a07834a0c807e20) but below the featured image.

**Comment by r-a-y** [comment]
Here's my take on the paper author block:

![Screenshot](https://cloud.githubusercontent.com/assets/505921/10955784/2a4d5356-830b-11e5-977f-372c1d6b604d.png)

I moved the paper author block below the title as I think this looks cleaner.

I haven't committed this yet.  Let me know what you think.

**Comment by mkgold** [comment]
Placement looks good to me. Does the color come from an established palette? Interested in @samradd's take

**Comment by r-a-y** [comment]
> Does the color come from an established palette?

What color are you referring to?  The green of the "Public Paper" status label?

**Comment by mkgold** [comment]
> What color are you referring to? The green of the "Public Paper" status label?

Yes

**Comment by r-a-y** [comment]
I believe the colors were pulled from the mockup that Chris and Sam made:
https://www.evernote.com/shard/s11/sh/2a92f7ca-7297-4a88-95fe-e21552e776be/3ad953afd37528809a07834a0c807e20

**Comment by samradd** [comment]
I agree that looks cleaner @r-a-y -- I assume it will be below the URL editor field during editing? (I can't remember if we've landed on this being visible during editing or not...)

The green did come from the mock-up which came from Chris. We don't use green elsewhere, that I can find/recall, to indicate private/public, so I'm okay with introducing it here and carrying it to other elements later once we have user feedback on it here. 
If we'd like to use an existing green from the site, there's the active-tab green from the homepage (#D4ECD6) though it's more subtle. 
![screen shot 2015-11-05 at 3 27 13 pm](https://cloud.githubusercontent.com/assets/7431171/10980753/b6ed5452-83d1-11e5-89f3-02a51aec6614.png)

**Comment by r-a-y** [comment]
The changes are now live on cdev for testing.

>  I assume it will be below the URL editor field during editing?

Yes, the paper author block does show below the URL editor.

> (I can't remember if we've landed on this being visible during editing or not...)

I think I do remember someone saying that the paper author block should not be shown during editing, but wasn't sure if it was something we wanted to implement.  It's not hard to do, just need a decision.

**Update** - We already have an issue open for this.  See #56.

**Comment by samradd** [comment]
> I think I do remember someone saying that the paper author block should not be shown during editing, but wasn't sure if it was something we wanted to implement. It's not hard to do, just need a decision.
> 
> Update - We already have an issue open for this. See #56.

Thanks for the reference! Yeah, let's just leave it for now in the beta.
