### ISSUE TITLE
Don't show author panel when in Edit mode

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#56]
From http://commons.gc.cuny.edu/?p=43668:

> The fields in the Author Info area are unable to be edited via-click in the edit interface and do not auto-update as you change elements within the settings fields. We recommend removing this area entirely in edit-mode so as so remove the expectation that you might be able to affect it directly.

This is not entirely true; the list of tags does update when you change the tags attached to the paper. Moreover, there is no other place to see tags when in Edit mode, except by clicking on the Tag button. For this reason, I'd suggest _not_ removing this at the moment.

cc @samradd @chris0stein for feedback

**Comment by samradd** [comment]
Ah, I didn't realize the tags update. I think that's a valid point -- let's leave it as is for now. Thanks, Boone!

**Comment by boonebgorges** [comment]
:+1:
