### ISSUE TITLE
User's Followed tab should not include user's own papers

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#73]
From http://commons.gc.cuny.edu/?p=44228

cc @samradd

**Comment by r-a-y** [comment]
I've made the change, but if we omit the displayed user's papers from the displayed user's "Followed Papers" tab, then what happens to the "Papers I follow" tab on the Papers directory?

Should we omit the logged-in user's papers from there as well?

**Comment by r-a-y** [comment]
@samradd - Just a friendly ping for some feedback here!

**Comment by samradd** [comment]
Sorry @r-a-y, missed this one in my review on Friday.

The 'Papers I Follow' tab should also omit the user's own papers, yes. Since they mirror each other, 'Papers I Follow' and 'Followed Papers' should probably also be titled the same. I vote for 'Papers I Follow' because I think it's clearer.

**Comment by r-a-y** [comment]
> The 'Papers I Follow' tab should also omit the user's own papers, yes.

Should be fixed on cdev.

>  I vote for 'Papers I Follow' because I think it's clearer.

My only issue with this is if you're viewing another member's followed papers, "Papers I Follow" would have to change to "Papers X follows" or something like that.  Do you have some other text we could use?  Otherwise, "Papers X follows" sounds a little convoluted.

**Comment by samradd** [comment]
> My only issue with this is if you're viewing another member's followed papers, "Papers I Follow" would have to change to "Papers X follows" or something like that.

Very valid point... I'm fine with leaving the titles as they are for now. I like the clarity of 'Papers I Follow' in the directory view, and can't think of a less convoluted title for the profile view.

**Comment by r-a-y** [comment]
Thanks for the reply, Sam!

Going to close this one for now.
