### ISSUE TITLE
Exit Edit mode when a paper is published

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#75]
See http://commons.gc.cuny.edu/?p=44238, http://commons.gc.cuny.edu/?p=44241

**Comment by boonebgorges** [comment]
ping @r-a-y I know that the above is pretty unpleasant. But getting this right without a refresh will include rebuilding the entire interface entirely with each change of `post_status`, which FEE makes it difficult to do - it does a fair amount of rebuilding on the server (like the Publish/Update stuff you built). Let's continue to work on this and hopefully we can rip the refresh out at some point.

**Comment by r-a-y** [comment]
That's fine with me!
