### ISSUE TITLE
Don't show 'paper_status' in Publish/Update menu

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#76]
we don't use this and it's confusing

See http://commons.gc.cuny.edu/?p=44239

**Comment by samradd** [comment]
@r-a-y I believe this was where we got rid of the arrow for 'published/draft' next to the Update button. This also appears to have re-appeared. 

![screen shot 2015-11-30 at 2 58 23 pm](https://cloud.githubusercontent.com/assets/7431171/11482786/d3041c3e-9772-11e5-8097-ce410d930849.png)

**Comment by r-a-y** [comment]
@samradd - I do not think we chose to remove the arrow; only options that were not applicable like "Sticky" and "Pending Review".  

The arrow has some relevance if one decides to change their published paper back to draft status.  However, I can remove the arrow for our usage on the Commons, but does this impact any of the documentation?

**Comment by samradd** [comment]
No, you're right, @r-a-y.

It's definitely included in the documentation (http://codex.commons.gc.cuny.edu/how-to-create-a-paper/), which is proof that I made up the removal. Let's leave it be.
