### ISSUE TITLE
Directory tabs should load via AJAX

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#86]
Copied from https://redmine.gc.cuny.edu/issues/4945

> As noted in http://commons.gc.cuny.edu/?p=44239 and by Matt in our 11/20 meeting, clicking on 'My Papers' or 'Papers I Follow' in the Papers Directory routes users to the corresponding sections in their commons profile (ex: http://cdev.gc.cuny.edu/members/samradd/papers/) rather than keeping them in the papers directory view. This should be updated to match the functionality of other pages like My Sites where 'My Sites' and 'Following' presents that information in-page rather than taking the user to their Commons Profile.

**Comment by r-a-y** [comment]
I see we made a commit in bp-nelo to disable AJAX:
https://github.com/cuny-academic-commons/cac/commit/33a869af6bc096907fb208dcfdb3c8f5a63d6ca2

And the reason behind this was due to complications with the paper tag filter.  Let me see what I can do here.

**Comment by boonebgorges** [comment]
Oh right. My memory is not what it used to be :-/

IIRC, I spent two minutes looking at bp_filter_request and gave up. It 
may be that we need to write a custom handler. In any case, it's not 
critical for CAC 1.9.

**Comment by r-a-y** [comment]
Okay, this should be fixed on cdev.
