### ISSUE TITLE
Always show Responses title above comments box

### ISSUE THREAD

**Issue by profstein** [cuny-academic-commons/social-paper#93]
Right now if you have a paper with no comment then the "Responses" title doesn't show above the comment box.

![image](https://cloud.githubusercontent.com/assets/6502138/11383964/d62b2df0-92d9-11e5-821a-ef1ec7018b66.png)

Once a comment is left, whether it is a post comment or paragraph comment, the title shows:
![image](https://cloud.githubusercontent.com/assets/6502138/11383995/02c8c502-92da-11e5-8f38-997e258c833f.png)

**Comment by boonebgorges** [comment]
Thanks. This seems like a straightforward bug, so let's fix it for v1.
