### ISSUE TITLE
Required plugin admin notice throws notice due to nonce generation

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/social-paper#95]
The admin notice related to required plugins is generated at 'plugins_loaded' (`Social_Paper::init`). The generation of nonces requires invoking the current user, and bbPress and BP throw a tantrum when the current user is referenced before 'init'. ("The current user is being initialized without using $wp->init()...") Can we move the generation of the admin notice to a later hook?

**Comment by r-a-y** [comment]
I have a fix ready for this.  Should I commit to 1.0.x or master?

**Comment by boonebgorges** [comment]
I think 1.0.x is what we're running on CAC, so maybe there and then 
merge to master? (it doesn't matter very much :) )

**Comment by r-a-y** [comment]
K, thanks!

Can you clarify a few things for me?  I'm getting a little confused with our branches.  Should master reflect whatever 1.0.x branch currently is?  What are we working on for 1.1.x branch?

**Comment by boonebgorges** [comment]
Hrm. I don't remember. I think the idea was:
- new features that will not launch anytime soon in 1.1.x
- bugfixes and features for immediate launch in 1.0.x
- merge things to master when they're ready to be deployed to CAC - 
  submodule is pinned against the head of the master branch
